# Site settings
title: Wayfaring Amy
email: amy@wayfaringamy.com
url: http://localhost:4000

# Meta
description: 
google-verification: -cfjXrFA-ZOxgLkJsOw-NiTznjYEDiDu08Rlz6kh8bI

# Extras
google-analytics:
gosquared: GSN-280144-X
disqus:
dropbox: https://dl.dropboxusercontent.com/u/39419177/wayfaringamy.com

# Blog settings
collections:
    travel:
        title: Travel
        output: true
        permalink: "/travel/:title/"
    thoughts:
        title: Thoughts
        output: true
        permalink: "/thoughts/:title/"
    calendar:
        title: Travel Dates
        output: false
        
defaults:
-
  scope:
    path: ''
    type: "travel"
  values:
    layout: default
    has_comments:
    master: true
    meta.sticky: "no"
- 
  scope:
    path: ''
    type: "thoughts"
  values:
    layout: default
    has_comments:
    master: true
    meta.sticky: "no"
- 
  scope:
    path: ''
    type: "calendar"
  values:
    master: false

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
#    style: compressed
exclude:
- CNAME
- README.md
- ".gitignore"
- ".sass-cache"
