---
title: Wayfaring Amy
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  thoughts:
    title: Thoughts
    output: true
    permalink: "/thoughts/:title/"
  travel:
    title: Travel
    output: true
    permalink: "/travel/:title/"
  calendar:
    title: Travel Dates
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: travel
  values:
    layout: default
    has_comments: 
    master: true
    meta.sticky: 'no'
- scope:
    path: ''
    type: thoughts
  values:
    layout: default
    has_comments: 
    master: true
    meta.sticky: 'no'
- scope:
    path: ''
    type: calendar
  values:
    master: false
email: amy@wayfaringamy.com
url: http://localhost:4000
description: 
google-verification: "-cfjXrFA-ZOxgLkJsOw-NiTznjYEDiDu08Rlz6kh8bI"
google-analytics: 
gosquared: GSN-280144-X
disqus: 
dropbox: https://dl.dropboxusercontent.com/u/39419177/wayfaringamy.com
markdown: kramdown
sass:
  sass_dir: _sass
exclude:
- CNAME
- README.md
- ".gitignore"
- ".sass-cache"
